### PR TITLE
Split into smallrye-build-parent and smallrye-parent

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
Woops

**Comment by jponge** [comment]
Got it right this time

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
@cescoffier would you like to review as well? Thanks!

**Comment by jponge** [comment]
The more BOM experts, the better 👍

**Comment by cescoffier** [comment]
It looks good to me. I would have clearly separated the two poms in two different modules. I'm not totally sure about having a parent using unrelated `modules`, it may cause issues when building the effective pom.

**Comment by jponge** [comment]
I can refactor have a root POM then the 2 modules, as you wish.

**Comment by jponge** [comment]
Here are the effective POMS: https://gist.github.com/jponge/c6263dc3492cd3622d77175862d68fb2

**Comment by cescoffier** [comment]
which includes:
```
    <modules>
      <module>full-parent</module>
    </modules>
```

So, if let's say Mutiny uses this pom as a parent, what would be the effective pom? If the module using it as a parent does not have a module, would it get one?

**Review by cescoffier — CHANGES_REQUESTED** [review]
(updating my review as I got a few questions)

**Comment by jponge** [comment]
My understanding is that a parent does not include a module, see the effective POMs in https://gist.github.com/jponge/c6263dc3492cd3622d77175862d68fb2

**Comment by jponge** [comment]
Let me check on Mutiny

**Comment by jponge** [comment]
Migrating Mutiny, here's what the Mutiny BOM would look like: https://gist.github.com/jponge/6cfc533fce94c046eaa3492c410044f2

**Comment by cescoffier** [comment]
Ok, it looks fine.

**Review by cescoffier — APPROVED** [review]

**Comment by jponge** [comment]
I got a lighter BOM for Mutiny in https://gist.github.com/jponge/93a95307ad0889c5e14e1c07d937c079

Still that PR does break into 2 parents, and it's already a plus for Mutiny itself.

**Comment by radcortez** [comment]
So, are we ok with the current state?

**Comment by jponge** [comment]
For me this PR improves the situation, does that make sense to the others?

**Comment by radcortez** [comment]
I think it will also help with the Jakarta 9 work. It opens up the option to add an additional module with `-jakarta` in the artifactId, and updates to the dependencies, so we can easily switch between one and the other.

**Pull request merged**
