### PR TITLE
Add documentation about using GitHub Actions

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
I have two questions that maybe @kenfinnigan can answer.  First question: why do you suppose CI has zombie'd out on this?  And second question: why do we need to do builds with JDK 11 and JDK 8 when this project is literally just a POM?

**Comment by kenfinnigan** [comment]
Could we have hit the GH Actions free limit for the month?

**Comment by dmlloyd** [comment]
Hm I think the zombie might be due to the change being done to a "ignored" path for the workflow - but the workflow is required, so it can't proceed :neutral_face:

**Comment by radcortez** [comment]
Yes, sometimes the action doesn't even start or quits in the middle so its gets into some zombie state. I don't think is anything to do with your stuff, but bugs from GH itself.

Usually, I have to rehash and push force the commit, to refresh and kick out a new build.

**Pull request merged**
