### PR TITLE
drop env-related MANIFEST properties

### PR DESCRIPTION
**Pull request by hboutemy**
JDK vendor and OS details make Reproducible Builds really hard to check

see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/smallrye/jandex/README.md

### CODE REVIEW

**Comment by dmlloyd** [comment]
Anyone have a comment? @radcortez, @Ladicek? I think this is probably OK

**Comment by radcortez** [comment]
Sure.

**Review by radcortez — APPROVED** [review]

**Comment by hboutemy** [comment]
thank you
now we need the release 40 to be done then used by jandex https://github.com/smallrye/jandex for the improvement to be visible in next jandex release

**Comment by dmlloyd** [comment]
I plan a release on Monday.

**Pull request merged**
