### PR TITLE
Upgrade the impsort Maven plugin

### PR DESCRIPTION
**Pull request by Ladicek**
The version 1.8.0 is the first version that works correctly with Maven 3.9.0+, see [1][2].

[1] https://github.com/revelc/impsort-maven-plugin/issues/64
[2] https://github.com/revelc/impsort-maven-plugin/pull/65

### CODE REVIEW

**Comment by radcortez** [comment]
Yes, I noticed the impsort issue yesterday with GH Windows builds. I was wondering why dependabot didn't update the plugin, and I've found this: https://github.com/smallrye/smallrye-parent/pull/338 :D
 
Our plan was to move to 11 with the Jakarta update, which is now done on Quarkus. I think it will be fine to mandate 11 from now on and only update parent in the Jakarta branches (or main if it is already Jakarta).

We do need to fix the Maven version in the build pipelines to be able to build the javax versions.

**Comment by Ladicek** [comment]
Hah, I looked for dependabot PR but didn't look far enough into the past :-)

Yeah I'm doing the same on Fault Tolerance: merging `jakarta` into `main`, which includes bumping to 11. So long, Java 8! :-)

**Comment by radcortez** [comment]
To fix the Maven version in the CI:
https://github.com/smallrye/smallrye-config/commit/6ddbf89b7c386d6c136bdac62a21b63d853eabe9

I think we should merge the Jakarta POM into the main one and drop it, meaning that instead of using `smallrye-parent-jakarta`, you use `smallrye-parent` again and bump Java to 11. This would mean the last parent version for the `javax` dependencies is `38`. If we need further updates, we either have to do a `x.y` release or override the SR project directly. Effectively, everything that is `javax` should be in maintenance mode now, so I do not expect requiring bumping their parent versions.

@cescoffier 
@sberyozkin 
@aureamunoz 
@jmartisk 
@xstefank 
@jponge 
@brunobat 
@MikeEdgar 
@phillip-kruger 
@ozangunalp

Does anyone have any concerns or restrictions?

**Comment by Ladicek** [comment]
I agree with removing the `javax` parent POM and keeping only the `jakarta` one (even though I use `build-parent` and manage dependencies myself :-) ).

**Review by jponge — APPROVED** [review]
Works for us on the Mutiny galaxy

**Review by radcortez — APPROVED** [review]

**Pull request merged**
